config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'users#index'
  # get 'comments/likes'
  resources :users, only: [:index, :show] do 
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
       resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # get '/users/:id', to: 'users#show'
  # get '/users/:id/posts', to: 'posts#index'
  # get '/users/:id/posts/new', to: 'posts#new', as: 'new_post' 
  # post '/users/:id/posts', to: 'posts#create' as: 'create_post'
  # get '/users/:id/posts/:id', to: 'posts#show'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :manage, Comment, user_id: user.id
      can :manage, Post, user_id: user.id
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  def current_user
    User.limit(1)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post

  def update_like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, numericality: { greater_than_or_equal_to: 0 }
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  def update_post_counter
    user.increment!(:posts_counter)
  end

  def recent_5_comments
    comments.order('created_at Desc').limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  # validates :name, presence: true
  # validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }
  has_many :comments, foreign_key: 'user_id'
  has_many :likes, foreign_key: 'user_id'
  has_many :posts, foreign_key: 'user_id'

  def recent_3_posts
    Post.last(3)
  end

  def admin?
    :role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    create_comment = current_user.comments.new(
      text: comment_params,
      user_id: current_user.id,
      post_id: @post.id
    )
    create_comment.update_comment_counter
    if create_comment.save
      redirect_to "/users/#{@post.user_id}/posts/#{@post.id}", success: 'Success!'
    else
      render :new, alert: 'Error: failed to save comment'
    end
  end

  def destroy
    @comment = Comment.find(params[:comment_id])
    @post = Post.find(@comment.post_id)
    @post.comments_counter -= 1
    @comment.destroy!
    @post.save
    flash[:success] = 'You have deleted this post!'
    redirect_to user_posts_path(current_user.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)[:text]
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    add_like = current_user.likes.new(
      user_id: current_user.id,
      post_id: @post.id
    )
    if add_like.save
      add_like.update_like_counter
      flash.now[:notice] = 'Post successfully added!'
      redirect_to user_posts_path(@post.id)
    else
      flash.now[:alert] = 'Error: failed to like post'
      redirect_to user_posts_path(current_user)
    end
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
   def index
   end
   
   def show
   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    # @posts = @user.posts
    @posts = @user.posts.includes(:comments)
  end

  def new
    new_post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { new_post: new_post } }
    end
  end

  def create
    create_post = current_user.posts.new(params.require(:data).permit(:title, :text))
    create_post.comments_counter = 0
    create_post.likes_counter = 0
    create_post.update_post_counter
    if create_post.save
      flash[:success] = 'Post successfully added!'
      redirect_to user_posts_path
    else
      flash[:error] = 'Error: Post could not be created'
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comments = @post.comments
  end

  def destroy
    post = Post.find(params[:id])
    user = User.find(params[:user_id])
    user.posts_counter -= 1
    post.destroy!
    user.save
    flash[:success] = 'You have deleted this post!'
    redirect_to user_posts_path(current_user.id)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
   def index
   end
   
   def show
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.recent_3_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_notify(flash_type)
    case flash_type
    when 'success'
      'bg-green-100 border border-green-400 text-green-700'
    when 'error'
      'bg-green-100 border border-red-400 text-red-700'
    else
      flash_type.to_s
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_nav_bar.html.erb
<nav class="flex justify-between flex-wrap bg-white p-6 font-mono items-center drop-shadow-sm">
  <div class="flex items-center ">
    <h2 class="font-semibold text-2xl text-indigo-500">Blog App</h2>
  </div>
  <div class="flex flex-row items-center gap-4">
    <div class="text-sm">
       <%= link_to "Authors", root_path, class:'block   text-indigo-500 hover:text-gray-300 mr-4' %>
    </div>
<% if user_signed_in? %>
  
<div>
    <%= link_to "New Post", new_user_post_path(current_user), class:'inline-block text-sm px-4 py-2 leading-none border rounded text-white bg-indigo-500 border-indigo-500 hover:border-indigo-500 hover:text-indigo-500 hover:bg-transparent'%>
    </div>
    <div>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:'inline-block text-sm px-4 py-2 leading-none border rounded text-white bg-indigo-500 border-indigo-500 hover:border-indigo-500 hover:text-indigo-500 hover:bg-transparent' %>
    </div>
<% else %>
       <div>
       <%= link_to "Sign In", new_user_session_path,class:'inline-block text-sm px-4 py-2 leading-none border rounded text-indigo-500 border-indigo-500 hover:border-transparent hover:text-white hover:bg-indigo-500 ' %>
    </div>
     <div>
      <%= link_to "Sign Up",  new_user_registration_path, class:'inline-block text-sm px-4 py-2 leading-none border rounded text-white bg-indigo-500 border-indigo-500 hover:border-indigo-500 hover:text-indigo-500 hover:bg-transparent ' %>
    </div>
<% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

<body class="bg-gray-50 font-mono">

<% flash.each do |type, message| %>
<div class="<%= flash_notify(type)%> px-4 py-3 rounded relative" role="alert">
  <span class="block sm:inline"><%= message %></span>
</div>
<% end %>

  <%= render "layouts/nav_bar"%>
  <main class='p-8'>
    <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_add_comment.html.erb
<h1 class='font-mono text-lg font-bold text-indigo-900 mb-2 mt-4'>Leave a comment</h1>
<%= form_with class:'flex flex-col gap-6', url: "#{@post.id}/comments", scope: :comment do |form| %>
  <%= form.text_area :text, class:'p-3 outline outline-1 outline-indigo-300 rounded-lg', placeholder: "Leave a comment", rows: "3" %>
  <%= form.submit "Submit", class:'bg-indigo-500 p-3 text-white rounded-lg drop-shadow-md' %>
<% end %>

app/views/posts/_post_comment.html.erb
<%= link_to "posts/#{post.id}", id: post.id do %>
<div
  class="flex flex-col rounded-lg font-mono gap-3 outline outline-1 outline-indigo-300 w-full p-4 bg-white shadow-sm mb-4"
>
  <h2 class="text-lg text-gray-700">
    <strong><%= post.title %></strong>
  </h2>
  <p class="text-gray-500"><%= post.text %></p>

  <div class="flex gap-4">
    <div class="p-2 outline outline-1 outline-indigo-300 rounded-lg font-bold">
      Comments: <%= post.comments_counter%>
    </div>
    <div class="p-2 outline outline-1 outline-indigo-300 rounded-lg font-bold">
      Likes: <%= post.likes_counter%>
    </div>
  </div>

  <div
    class="flex flex-col rounded-lg font-mono gap-1 outline outline-1 outline-indigo-300 w-full p-4 bg-indigo-50"
  >
    <% post.comments.each do |comment| %>
    <p class="text-sm">
      <span class="font-bold"><%= comment.user.name %></span> <%= comment.text%>
    </p>
    <%end%>
  </div>
</div>
<% end %>

app/views/posts/index.html.erb
<div class='mb-4 flex flex-row justify-between items-center'>
<h1 class='font-mono text-2xl font-bold text-indigo-900 '>Author Posts</h1>
</div>

<div class='flex flex-col gap-4'>
<%= render "shared/header" %>

<div class='p-4 bg-white rounded-lg mb-4 outline outline-1 outline-indigo-300'>
<% @posts.each do |post| %>
<%= render "post_comment", post: post %>
<% end %>
</div>

<button class='bg-indigo-500 p-2 text-white rounded-lg drop-shadow-md'>Pagination<button>
</div>

app/views/posts/new.html.erb
<h1 class='font-mono text-2xl font-bold text-indigo-500 mb-4'>New post</h1>
<%= form_with class:'flex flex-col gap-6', url: user_posts_path, scope: :data do |form| %>
  <%= form.text_field   :title, class:'p-3 outline outline-1 outline-indigo-300 rounded-lg', placeholder: "Post title" %>
  <%= form.text_area :text, class:'p-3 outline outline-1 outline-indigo-300 rounded-lg', placeholder: "Post body", rows: "12" %>
  <%= form.submit "Post", class:'bg-indigo-500 p-3 text-white rounded-lg drop-shadow-md' %>
<% end %>

app/views/posts/show.html.erb
<div class='flex flex-col  rounded-lg font-mono gap-3 outline outline-1 outline-indigo-300 w-full p-4 bg-white shadow-sm mb-4'>
<div class='flex flex-row justify-between items-center'>
<div class='flex flex-row items-center gap-4'>
<h2 class='text-lg text-gray-700'>
<strong><%= @post.title %></strong>
</h2>
<%= form_with url: "#{@post.id}/likes", scope: :like do |form| %>
  <%= form.submit "Like Post", class:'bg-indigo-300 hover:bg-indigo-400 text-white p-2 rounded-lg inline-flex items-center text-sm' %>
<% end %>
   <%if can? :destroy, @post %>
          <%= button_to "Delete Post",  user_post_path, :method => :delete, data: {confirm: 'Are You Sure You Want to Delete This Post'},  class:'inline-block text-sm px-4 py-2 leading-none border rounded text-white bg-red-500  hover:bg-red-700 hover:text-white ' %>
   <%end%>



</div>
<div class='flex gap-4'>
<div class='p-2 outline outline-1 outline-indigo-300 rounded-lg font-bold'>
Comments: <%= @post.comments_counter || 0 %>
</div>
<div class='p-2 outline outline-1 outline-indigo-300 rounded-lg font-bold'>
Likes: <%= @post.likes_counter || 0 %>
</div>
</div>
</div>
<p class='text-gray-600'><%= @post.text %></p>
</div>
<div class='flex flex-col  rounded-lg font-mono gap-4 outline outline-1 outline-indigo-300 w-full p-4 bg-indigo-50'>
<% @comments.each do |comment| %>
<div class='flex flex-row items-center'>
<p class='text-sm mr-2'><span class='font-bold'><%= comment.user.name %>: </span><%= comment.text%></p>
  <%if can? :destroy, @post %>
<span> | </span>
 <%= link_to "delete comment",  user_post_comment_path(comment_id: comment.id,  post_id: @post.id),  data: {  turbo_method: :delete,
                    turbo_confirm: "Are you sure?"}, class:'ml-2 inline-block text-sm  leading-none text-indigo underline hover:underline-offset-4 hover:text-red-500' %>
 <%end%>
</div>
<%end%>
</div>

<%= render 'add_comment', post: @posts%>

app/views/shared/_header.html.erb
<div class="flex flex-row  rounded-lg font-mono gap-4">
<%= image_tag 'https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2680&q=80', class:"rounded-lg w-36 h-24 object-cover"%> 
<div class='rounded-lg outline outline-1 outline-indigo-300 w-full p-4 bg-white'>
<h2 class='text-xl text-gray-700'>
<strong><%= @user.name %></strong>
</h2>
<p class='text-gray-400'>number of posts:
 <span class='font-bold text-indigo-500'> <%= @user.posts_counter || 0 %></span>
<p>
</div>
</div>





app/views/users/_post.html.erb
<div class='flex flex-col  rounded-lg font-mono gap-3 outline outline-1 outline-indigo-300 w-full p-4 bg-white shadow-sm'>
<h2 class='text-lg text-gray-700'>
<strong><%=post.title%></strong>
</h2>
<p class='text-gray-500'><%=post.text%></p>
<div class='flex gap-4'>

<div class='p-2 outline outline-1 outline-indigo-300 rounded-lg font-bold'>
Comments: 0
</div>
<div class='p-2 outline outline-1 outline-indigo-300 rounded-lg font-bold'>
Likes: 0
</div>
</div>
</div>

app/views/users/_show_bio.html.erb
<div class='flex flex-col  rounded-lg font-mono gap-3 outline outline-1 outline-indigo-300 w-full p-4 bg-white'>
<h2 class='text-lg text-gray-700 font-bold'>Bio:</h2>
<p>
<%= @user.bio %>
</p>
</div>

app/views/users/_show_header.html.erb
<div class="flex flex-row  rounded-lg font-mono gap-4">
<%= image_tag 'https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2680&q=80', class:"rounded-lg w-36 h-24 object-cover"%>
<div class='rounded-lg outline outline-1 outline-indigo-300 w-full p-4 bg-white'>
<h2 class='text-xl text-gray-700'>
<strong><%= @user.name %></strong>
</h2>
<p class='text-gray-400'>number of posts:
 <span class='font-bold text-indigo-500'> <%= @user.posts_counter || 0 %></span>
<p>
</div>
</div>





app/views/users/_user.html.erb
<%= link_to user do %>
<div id="<%= dom_id user%>" class="flex flex-row p-4 bg-white rounded-lg shadow-md mb-4  gap-3 outline outline-1 outline-indigo-300 font-mono">
<%= image_tag 'https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2680&q=80', class:"rounded-lg w-36 h-24 object-cover" %>
<div>
<h2 class='text-xl text-gray-700'>
<strong><%= user.name %></strong>
</h2>
<p class='text-gray-400'>number of posts:
 <span class='font-bold text-indigo-500'><%= user.posts_counter || 0 %></span>
<p>
</div>
</div>
<% end %>




app/views/users/index.html.erb
<h1 class='font-mono text-2xl font-bold text-indigo-900 mb-4'>Users</h1>
<div id="users" class="users">
<% @users.each do |user| %>
<%= render user%>
<% end %>
</div>

app/views/users/show.html.erb
<h1 class='font-mono text-2xl font-bold text-indigo-900 mb-4'>Author Details</h1>
<div class='flex flex-col gap-4'>
<%= render "shared/header" %>
<%= render "show_bio" %>
<div class='flex flex-col  rounded-lg font-mono gap-3 outline outline-1 outline-indigo-300 w-full p-4 bg-white'>
<h2 class='text-lg text-gray-700 font-bold'>Recent Posts:</h2>
<% @posts.each do |post| %>
<%= render "post", post: post%>
<% end %>
</div>
<a href="<%= @user.id %>/posts" class="btn btn-primary">
<button class='bg-indigo-500 p-2 text-white rounded-lg drop-shadow-md w-full'>See all posts<button>
</a>
</div>
